
TG_CAT_JEWELCRAFTING = "Jewels";

TG_DB_JEWELS = {
    -- JEWELCRAFTING --
    { tag = 774,     name = "Malachite",          cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 818,     name = "Tigerseye",          cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 1206,    name = "Moss Agate",         cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 1210,    name = "Shadowgem",          cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 1529,    name = "Jade",               cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 1705,    name = "Lesser Moonstone",   cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 3864,    name = "Citrine",            cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 7909,    name = "Aquamarine",         cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 7910,    name = "Star Ruby",          cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 12361,   name = "Blue Sapphire",      cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 12364,   name = "Huge Emerald",       cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 12799,   name = "Large Opal",         cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 12800,   name = "Azerothian Diamond", cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 21929,   name = "Flame Spessarite",   cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 23077,   name = "Blood Garnet",       cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 23079,   name = "Deep Peridot",       cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 23107,   name = "Shadow Draenite",    cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 23112,   name = "Golden Draenite",    cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 23117,   name = "Azure Moonstone",    cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 23436,   name = "Living Ruby",        cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 23437,   name = "Talasite",           cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 23438,   name = "Star of Elune",      cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 23439,   name = "Noble Topaz",        cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 23440,   name = "Dawnstone",          cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 23441,   name = "Nightseye",          cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 24243,   name = "Adamantite Powder",  cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 36917,   name = "Bloodstone",         cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 36918,   name = "Scarlet Ruby",       cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 36919,   name = "Cardinal Ruby",      cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 36920,   name = "Sun Crystal",        cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 36921,   name = "Autumn's Glow",      cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 36922,   name = "King's Amber",       cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 36923,   name = "Chalcedony",         cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 36924,   name = "Sky Sapphire",       cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 36925,   name = "Majestic Zircon",    cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 36926,   name = "Shadow Crystal",     cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 36927,   name = "Twilight Opal",      cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 36928,   name = "Dreadstone",         cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 36929,   name = "Huge Citrine",       cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 36930,   name = "Monarch Topaz",      cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 36931,   name = "Ametrine",           cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 36932,   name = "Dark Jade",          cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 36933,   name = "Forest Emerald",     cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 36934,   name = "Eye of Zul",         cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 46849,   name = "Titanium Powder",    cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 52177,   name = "Carnelian",          cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 52178,   name = "Zephyrite",          cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 52179,   name = "Alicite",            cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 52180,   name = "Nightstone",         cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 52181,   name = "Hessonite",          cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 52182,   name = "Jasper",             cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 52190,   name = "Inferno Ruby",       cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 52191,   name = "Ocean Sapphire",     cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 52192,   name = "Dream Emerald",      cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 52193,   name = "Ember Topaz",        cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 52194,   name = "Demonseye",          cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 52195,   name = "Amberjewel",         cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 52327,   name = "Volatile Earth",     cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 76130,   name = "Tiger Opal",         cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 76131,   name = "Primordial Ruby",    cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 76133,   name = "Lapis Lazuli",       cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 76134,   name = "Sunstone",           cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 76135,   name = "Roguestone",         cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 76136,   name = "Pandarian Garnet",   cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 76137,   name = "Alexandrite",        cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 76138,   name = "River's Heart",      cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 76139,   name = "Wild Jade",          cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 76140,   name = "Vermilion Onyx",     cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 76141,   name = "Imperial Amethyst",  cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 76142,   name = "Sun's Radiance",     cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 90407,   name = "Sparkling Shard",    cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 129099,  name = "Gem Chip",           cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 129100,  name = "Gem Chip",           cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 130172,  name = "Sangrite",           cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 130173,  name = "Deep Amber",         cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 130174,  name = "Azsunite",           cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 130175,  name = "Chaotic Spinel",     cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 130176,  name = "Skystone",           cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 130177,  name = "Queen's Opal",       cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 130179,  name = "Eye of Prophecy",    cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 130180,  name = "Dawnlight",          cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 130181,  name = "Pandemonite",        cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 130182,  name = "Maelstrom Sapphire", cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 130183,  name = "Shadowruby",         cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 130200,  name = "Gem Chip",           cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 130201,  name = "Gem Chip",           cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 130202,  name = "Gem Chip",           cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 130203,  name = "Gem Chip",           cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 130204,  name = "Gem Chip",           cat = TG_CAT_JEWELCRAFTING,  skill = 1 },
    { tag = 151579,  name = "Labradorite",        cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 151718,  name = "Argulite",           cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 151719,  name = "Lightsphene",        cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 151722,  name = "Florid Malachite",   cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 153700,  name = "Golden Beryl",       cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 153701,  name = "Rubellite",          cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 153702,  name = "Kubiline",           cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 153703,  name = "Solstone",           cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 153704,  name = "Viridium",           cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 153705,  name = "Kyanite",            cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 153706,  name = "Kraken's Eye",       cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 154120,  name = "Owlseye",            cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 154121,  name = "Scarlet Diamond",    cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 154122,  name = "Tidal Amethyst",     cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 154123,  name = "Amberblaze",         cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 154124,  name = "Laribole",           cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  
    { tag = 154125,  name = "Royal Quartz",       cat = TG_CAT_JEWELCRAFTING,  skill = 1 },  

}

TGJ_PLUGIN_CATEGORIES = {
    { db = TG_DB_JEWELS,  name = TG_CAT_JEWELCRAFTING, smenu = TG_PREFIX_SHOW..TG_CAT_JEWELCRAFTING,    profession = "Jewelcrafting", skill = 1 }
}

TGJ_MINABLES = {}